import './globals.css'

import {NextUIProvider} from '@nextui-org/react'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <NextUIProvider>
      <body>{children}</body>
    </NextUIProvider>
  )
}
